;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
        delete-horizontal-space
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-yank
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
